import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navbar";


const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata = {
  title: "nama tempat rental",
  description: "Generated by create next app",
    icons: {
		// icon: "/"
	  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} antialiased w-screen h-screen bg-white`}
      >
        <Navbar />
        {children}
      </body>
    </html>
  );
}
